#!/usr/bin/env bash
# Install the `lockscope` command and its two pinned parsers.
#
# The parsers go into a virtual environment that belongs to this installation,
# never into the system interpreter: a system Python that refuses `pip install`
# (PEP 668, the default on current macOS and several distributions) is correct
# to refuse, and working around it with --break-system-packages breaks the
# user's machine to install a linter.
set -euo pipefail

PREFIX="${LOCKSCOPE_PREFIX:-$HOME/.local}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARE="$PREFIX/share/lockscope"
BIN="$PREFIX/bin"
VENV="$SHARE/venv"

PYTHON="${PYTHON:-python3}"
if ! command -v "$PYTHON" >/dev/null 2>&1; then
  echo "lockscope: python3 is required" >&2
  exit 1
fi

version_ok=$("$PYTHON" -c 'import sys; print(1 if sys.version_info >= (3, 10) else 0)')
if [ "$version_ok" != "1" ]; then
  echo "lockscope: Python 3.10 or newer is required" >&2
  exit 1
fi

if ! "$PYTHON" -c 'import venv' >/dev/null 2>&1; then
  echo "lockscope: the python3 venv module is missing (Debian/Ubuntu: apt install python3-venv)" >&2
  exit 1
fi

mkdir -p "$SHARE" "$BIN"
rm -rf "$SHARE/src"
cp -R "$HERE/src" "$SHARE/src"
cp "$HERE/requirements.txt" "$SHARE/requirements.txt"

# Idempotent: an existing environment is reused, and pinned versions mean a
# second run installs nothing new.
if [ ! -x "$VENV/bin/python" ]; then
  "$PYTHON" -m venv "$VENV"
fi
"$VENV/bin/python" -m pip install --quiet --upgrade pip >/dev/null
"$VENV/bin/python" -m pip install --quiet --require-hashes --no-deps -r "$SHARE/requirements.txt" 2>/dev/null \
  || "$VENV/bin/python" -m pip install --quiet -r "$SHARE/requirements.txt"

cat > "$BIN/lockscope" <<LAUNCHER
#!/usr/bin/env bash
# Generated by lockscope/install.sh — edit the skill, not this file.
export PYTHONPATH="$SHARE/src\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$VENV/bin/python" -m lockscope "\$@"
LAUNCHER
chmod +x "$BIN/lockscope"

echo "installed lockscope into $BIN/lockscope"
"$BIN/lockscope" --version
if ! printf '%s' "$PATH" | tr ':' '\n' | grep -qx "$BIN"; then
  echo "note: $BIN is not on your PATH"
fi
