#!/usr/bin/env bash
# Remove exactly what install.sh created, and nothing else.
set -euo pipefail

PREFIX="${LOCKSCOPE_PREFIX:-$HOME/.local}"
SHARE="$PREFIX/share/lockscope"
LAUNCHER="$PREFIX/bin/lockscope"

removed=0
if [ -f "$LAUNCHER" ] && grep -q "Generated by lockscope/install.sh" "$LAUNCHER" 2>/dev/null; then
  rm -f "$LAUNCHER"
  removed=1
fi
if [ -d "$SHARE" ]; then
  rm -rf "$SHARE"
  removed=1
fi
if [ "$removed" = "1" ]; then
  echo "removed lockscope from $PREFIX"
else
  echo "nothing to remove in $PREFIX"
fi
