#!/usr/bin/env python3
"""Build the static marketplace in site/ from the registry. Standard library only.

The site is generated from exactly the same data the README and the client use, so
it cannot drift into describing a skill that is not there. It is plain files: no
build step, no framework, no external request at runtime — searching and filtering
happen in the browser over data embedded in the page.

    python3 tools/build_site.py            # write site/
    python3 tools/build_site.py --check    # exit 3 if site/ is out of date
"""

from __future__ import annotations

import argparse
import html
import json
import shutil
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
REGISTRY = REPO / "registry" / "skills.json"
HISTORY = REPO / "registry" / "history.json"
SITE = REPO / "site"
ASSETS = REPO / "assets"
REPO_SLUG = "BEKO2210/SkillQuarry"
SOURCE_URL = f"https://github.com/{REPO_SLUG}"
EXIT_STALE = 3

CATEGORY_LABELS = {
    "autonomous": "Autonomous agents", "security": "Security", "coding": "Coding",
    "testing": "Testing", "ui-ux": "UI / UX", "devops": "DevOps", "mobile": "Mobile",
    "web": "Web", "documentation": "Documentation", "integrations": "Integrations",
    "utilities": "Utilities",
}
AGENT_LABELS = {
    "claude-code": "Claude Code", "agent-neutral-manual-mode": "Any agent (manual mode)",
    "codex": "Codex", "gemini": "Gemini", "mcp": "MCP",
}


class SiteError(RuntimeError):
    """The site cannot be built from what is on disk."""


def esc(value: Any) -> str:
    return html.escape(str(value), quote=True)


def _display(path: Path) -> str:
    """Repository-relative where possible; absolute otherwise, never an exception."""
    try:
        return path.relative_to(REPO).as_posix()
    except ValueError:
        return str(path)


def load_registry() -> list[dict[str, Any]]:
    try:
        document = json.loads(REGISTRY.read_text("utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise SiteError(f"cannot read {_display(REGISTRY)}: {exc}") from exc
    skills = document.get("skills")
    if not isinstance(skills, list) or not skills:
        raise SiteError("registry has no skills; run tools/render_readme.py first")
    return skills


def load_history() -> dict[str, Any]:
    """Version history, generated by tools/build_history.py from git."""
    try:
        document = json.loads(HISTORY.read_text("utf-8"))
    except FileNotFoundError as exc:
        raise SiteError("registry/history.json is missing; run tools/build_history.py") from exc
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise SiteError(f"cannot read {_display(HISTORY)}: {exc}") from exc
    skills = document.get("skills")
    if not isinstance(skills, dict):
        raise SiteError("history file has no skills object")
    return skills


def load_manifest(skill: dict[str, Any]) -> dict[str, Any]:
    path = REPO / str(skill.get("path", "")) / "skill.json"
    try:
        return json.loads(path.read_text("utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise SiteError(f"cannot read {path}: {exc}") from exc


STYLE = """
/* Inter, shipped with the site. No font CDN: the page still loads nothing from a
   third party, and the text is readable before the file arrives. */
@font-face {
  font-family: "InterVariable";
  src: url("assets/fonts/InterVariable.woff2") format("woff2");
  font-weight: 100 900;
  font-style: normal;
  font-display: swap;
}
:root {
  --ground: #0a1016; --raised: #111b24; --raised-2: #16222c; --edge: #223140;
  --ink: #f2f7fa; --muted: #a8c0cf; --dim: #6f8798;
  --accent: #ffd479; --accent-deep: #f0932b; --accent-soft: rgba(255, 212, 121, .12);
  --ok: #4ade80; --warn: #fbbf24;
  /* Golden ratio drives type, spacing and columns: every step is x1.618. */
  --phi: 1.618;
  --s1: 8px; --s2: 13px; --s3: 21px; --s4: 34px; --s5: 55px; --s6: 89px; --s7: 144px;
  --t1: 13px; --t2: 15px; --t3: 17px; --t4: 21px; --t5: 27px; --t6: 44px; --t7: 71px;
  --radius: 16px; --radius-sm: 10px;
  --shadow: 0 1px 2px rgba(0,0,0,.4), 0 12px 32px -18px rgba(0,0,0,.9);
  --page: 1140px;
  --hero-top: #16222c; --hero-bottom: #0a1016;
  --hero-scrim: rgba(10,16,22,.92); --hero-scrim-mid: rgba(10,16,22,.72); --hero-scrim-end: rgba(10,16,22,.35);
  --on-hero: #f2f7fa; --on-hero-muted: #c4d6e2;
  color-scheme: dark;
}
:root[data-theme="light"] {
  --ground: #eef2f6; --raised: #ffffff; --raised-2: #f3f7fa; --edge: #ccd8e2;
  --ink: #0c1821; --muted: #3d5b72; --dim: #64809a;
  --accent: #92560a; --accent-deep: #6f4106; --accent-soft: rgba(146, 86, 10, .12);
  --ok: #16794a; --warn: #8a5a06;
  --shadow: 0 1px 2px rgba(16,32,44,.06), 0 14px 34px -22px rgba(16,32,44,.5);
  --hero-top: #dde8f0; --hero-bottom: #eef2f6;
  --hero-scrim: rgba(8,14,20,.90); --hero-scrim-mid: rgba(8,14,20,.70); --hero-scrim-end: rgba(8,14,20,.34);
  --on-hero: #ffffff; --on-hero-muted: #d9e6ef;
  color-scheme: light;
}
* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  margin: 0; background: var(--ground); color: var(--ink);
  font: 16px/1.65 "InterVariable", "Inter", "Segoe UI", -apple-system, "Helvetica Neue", Arial, sans-serif;
  font-feature-settings: "cv05" 1, "cv08" 1, "ss03" 1;
  -webkit-font-smoothing: antialiased; text-rendering: optimizeLegibility;
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
:focus-visible { outline: 2px solid var(--accent); outline-offset: 3px; border-radius: 4px; }
.wrap { max-width: var(--page); margin: 0 auto; padding: 0 var(--s4); }

/* ---------- top bar ---------- */
.bar {
  position: sticky; top: 0; z-index: 30; background: color-mix(in srgb, var(--ground) 88%, transparent);
  backdrop-filter: blur(10px); border-bottom: 1px solid var(--edge);
}
.bar .wrap { display: flex; align-items: center; gap: 14px; height: 60px; }
.bar .mark { display: flex; align-items: center; gap: 10px; font-weight: 700; color: var(--ink); letter-spacing: .01em; }
.bar .mark:hover { text-decoration: none; }
.bar .mark img { width: 30px; height: 30px; border-radius: 8px; }
.bar .mark span i { font-style: normal; color: var(--accent); }
.bar nav { margin-left: auto; display: flex; align-items: center; gap: 18px; font-size: 14px; }
.bar nav a { color: var(--muted); }
.bar nav a:hover { color: var(--ink); text-decoration: none; }
.ghost {
  font: inherit; font-size: 14px; cursor: pointer; color: var(--muted);
  background: transparent; border: 1px solid var(--edge); border-radius: 999px;
  padding: 5px 12px; line-height: 1;
}
.ghost:hover { color: var(--accent); border-color: var(--accent-deep); }

/* ---------- hero ---------- */
.hero { position: relative; overflow: hidden; border-bottom: 1px solid var(--edge); isolation: isolate; }
.hero .shot { position: absolute; inset: 0; z-index: -2; }
.hero .shot img, .hero .shot video { width: 100%; height: 100%; object-fit: cover; display: block; }
.hero .shot video { position: absolute; inset: 0; }
.hero .shot video[hidden] { display: none; }
.hero::before {
  content: ""; position: absolute; inset: 0; z-index: -1; pointer-events: none;
  background:
    radial-gradient(1200px 520px at 18% 10%, rgba(10,16,22,.72), transparent 70%),
    linear-gradient(100deg, var(--hero-scrim) 0%, var(--hero-scrim-mid) 52%, var(--hero-scrim-end) 100%);
}
.hero .layers { position: absolute; inset: auto 0 0 0; height: 190px; opacity: .28; pointer-events: none; z-index: -1; }
.hero .wrap { position: relative; padding: var(--s6) var(--s3) var(--s5); max-width: var(--page); }
.hero .inner { max-width: calc(var(--page) / var(--phi)); }
.eyebrow {
  display: inline-flex; align-items: center; gap: var(--s1); font-size: var(--t1); letter-spacing: .12em;
  text-transform: uppercase; color: #ffd479; border: 1px solid rgba(255,212,121,.34);
  background: rgba(10,16,22,.55); border-radius: 999px; padding: 6px 15px; margin: 0 0 var(--s3);
  backdrop-filter: blur(6px);
}
.hero h1 { margin: 0; font-size: clamp(var(--t6), 4.4vw, 56px); line-height: 1.08;
  letter-spacing: -.025em; font-weight: 800; color: var(--on-hero); text-wrap: balance; }
/* The second sentence gets its own line where there is room, and simply
   follows the first — with a space — where there is not. */
@media (min-width: 1101px) { .hero h1 .line { display: block; } }
.hero h1 i { font-style: normal; color: var(--accent); }
.hero .lede { margin: var(--s3) 0 0; max-width: 58ch; font-size: var(--t3); color: var(--on-hero-muted); }
.actions { display: flex; flex-wrap: wrap; gap: var(--s2); margin: var(--s4) 0 0; }
.button {
  display: inline-flex; align-items: center; gap: 8px; border-radius: 999px; padding: 11px 22px;
  font-size: 15px; font-weight: 600; border: 1px solid transparent; transition: transform .12s ease;
}
.button:hover { text-decoration: none; transform: translateY(-1px); }
.button.primary { background: linear-gradient(135deg, var(--accent), var(--accent-deep)); color: #14202b; }
.button.secondary { border-color: rgba(255,255,255,.28); background: rgba(255,255,255,.08); color: #fff; backdrop-filter: blur(6px); }
.cta .button.secondary, main .button.secondary { border-color: var(--edge); background: var(--raised); color: var(--ink); backdrop-filter: none; }
.stats { display: flex; flex-wrap: wrap; gap: 26px; margin: 34px 0 0; padding: 0; list-style: none; }
.stats li { display: flex; flex-direction: column; }
.stats { gap: var(--s5); margin-top: var(--s4); }
.stats b { font-size: var(--t5); line-height: 1.2; color: var(--on-hero); letter-spacing: -.01em; }
.stats span { font-size: var(--t1); letter-spacing: .08em; text-transform: uppercase; color: var(--on-hero-muted); }

/* ---------- filter panel ---------- */
.panel {
  background: var(--raised); border: 1px solid var(--edge); border-radius: var(--radius);
  padding: 18px; margin: -28px 0 0; position: relative; z-index: 5; box-shadow: var(--shadow);
}
.controls { display: grid; gap: 12px; grid-template-columns: 1.6fr repeat(4, 1fr); }
.controls label { display: block; font-size: 12px; letter-spacing: .06em; text-transform: uppercase; color: var(--dim); margin-bottom: 6px; }
input, select {
  width: 100%; padding: 10px 12px; border-radius: var(--radius-sm); font: inherit; font-size: 15px;
  background: var(--raised-2); color: var(--ink); border: 1px solid var(--edge);
}
.toggles { display: flex; gap: 20px; flex-wrap: wrap; margin: 14px 2px 0; color: var(--muted); font-size: 14px; }
.toggles label { display: inline-flex; align-items: center; gap: 8px; margin: 0; text-transform: none; letter-spacing: 0; font-size: 14px; color: var(--muted); }
.toggles input { width: auto; }
@media (max-width: 900px) { .controls { grid-template-columns: 1fr 1fr; } }
@media (max-width: 560px) { .controls { grid-template-columns: 1fr; } }

/* ---------- sections ---------- */
main { padding-bottom: 20px; }
.section-head { display: flex; align-items: baseline; justify-content: space-between; gap: 16px; margin: 46px 0 2px; }
.section-head h2 { margin: 0; font-size: 13px; letter-spacing: .14em; text-transform: uppercase; color: var(--dim); }
.section-head a, .section-head span { font-size: 13px; color: var(--dim); }
.count { color: var(--dim); font-size: 14px; margin: 10px 2px 14px; }

/* ---------- cards ---------- */
.grid { display: grid; gap: 18px; grid-template-columns: repeat(auto-fill, minmax(330px, 1fr)); }
.card {
  position: relative; background: var(--raised); border: 1px solid var(--edge);
  border-radius: var(--radius); padding: 22px; display: flex; flex-direction: column; gap: 12px;
  transition: transform .14s ease, border-color .14s ease, box-shadow .14s ease;
}
.card:hover { transform: translateY(-3px); border-color: color-mix(in srgb, var(--accent-deep) 55%, var(--edge)); box-shadow: var(--shadow); }
.card { padding: 0; overflow: hidden; }
.card > *:not(.art) { margin-left: var(--s4); margin-right: var(--s4); }
.card > .top { margin-top: var(--s4); }
.card > .foot { margin-bottom: 0; padding-bottom: var(--s4); }
.art { position: relative; aspect-ratio: 16 / 9; overflow: hidden; background: var(--raised-2); }
.art img { width: 100%; height: 100%; object-fit: cover; display: block;
  transition: transform .5s cubic-bezier(.22,.75,.3,1); }
.card:hover .art img { transform: scale(1.045); }
.art::after { content: ""; position: absolute; inset: 0;
  background: linear-gradient(180deg, transparent 45%, var(--raised)); }
.art-icon { display: grid; place-items: center; }
.art-icon img { width: 42%; height: auto; object-fit: contain; }
.card .top { display: flex; align-items: center; gap: 13px; }
.card .top img { width: 52px; height: 52px; border-radius: 13px; flex: none; }
.card h3 { margin: 0; font-size: 19px; letter-spacing: -.01em; }
.card h3 a { color: var(--ink); }
.card h3 a::after { content: ""; position: absolute; inset: 0; }
.card .tagline { color: var(--accent); font-size: 13.5px; margin: 2px 0 0; }
.card p.body { margin: 0; color: var(--muted); font-size: 15px; }
.tags { display: flex; flex-wrap: wrap; gap: 7px; margin-top: auto; }
.tag {
  font-size: 12px; padding: 3px 10px; border-radius: 999px;
  border: 1px solid var(--edge); color: var(--muted); background: var(--raised-2);
}
.tag.ok { color: var(--ok); border-color: color-mix(in srgb, var(--ok) 40%, var(--edge)); }
.tag.warn { color: var(--warn); border-color: color-mix(in srgb, var(--warn) 40%, var(--edge)); }
.tag.accent { color: var(--accent); border-color: color-mix(in srgb, var(--accent-deep) 45%, var(--edge)); }
.card .foot {
  display: flex; align-items: center; justify-content: space-between; gap: 12px;
  border-top: 1px solid var(--edge); padding-top: 12px; font-size: 13px; color: var(--dim);
}
.installs b { color: var(--accent); }
.empty {
  color: var(--muted); text-align: center; border: 1px dashed var(--edge);
  border-radius: var(--radius); padding: 46px 20px; margin: 4px 0 0;
}

/* ---------- strips, keywords, cta ---------- */
.strip { display: flex; flex-wrap: wrap; gap: 10px; margin: 12px 0 0; padding: 0; list-style: none; }
.strip li {
  border: 1px solid var(--edge); border-radius: 999px; padding: 7px 15px;
  background: var(--raised); font-size: 14px;
}
.strip .when { color: var(--dim); margin-left: 6px; font-size: 13px; }
.cloud { display: flex; flex-wrap: wrap; gap: 8px; margin: 12px 0 0; padding: 0; list-style: none; }
.cloud button {
  font: inherit; font-size: 13px; cursor: pointer; padding: 5px 13px; border-radius: 999px;
  background: var(--raised); color: var(--muted); border: 1px solid var(--edge); transition: all .12s ease;
}
.cloud button:hover { color: var(--accent); border-color: var(--accent-deep); background: var(--accent-soft); }
.cta {
  display: grid; gap: 18px; grid-template-columns: 1.4fr 1fr; align-items: center;
  border: 1px solid var(--edge); border-radius: var(--radius); background:
    linear-gradient(135deg, var(--accent-soft), transparent 60%), var(--raised);
  padding: 30px; margin: 46px 0 10px;
}
.cta h2 { margin: 0 0 8px; font-size: 24px; letter-spacing: -.01em; }
.cta p { margin: 0; color: var(--muted); }
.cta .links { display: flex; flex-wrap: wrap; gap: 10px; }
@media (max-width: 800px) { .cta { grid-template-columns: 1fr; } }

/* ---------- detail pages ---------- */
.detail-hero { border-bottom: 1px solid var(--edge); background: linear-gradient(180deg, var(--raised), var(--ground)); }
.detail-hero .wrap { padding: 40px 24px 34px; }
.detail-hero .top { display: flex; align-items: center; gap: 18px; }
.detail-hero img.icon { width: 76px; height: 76px; border-radius: 19px; flex: none; }
.detail-hero h1 { margin: 0; font-size: clamp(30px, 4vw, 42px); letter-spacing: -.02em; }
.detail-hero .subtitle { color: var(--accent); margin: 6px 0 0; font-size: 17px; }
.crumbs { font-size: 13px; color: var(--dim); margin: 0 0 18px; }
.layout { display: grid; gap: var(--s4); grid-template-columns: minmax(0, 1.618fr) minmax(0, 1fr);
  padding: var(--s4) 0 10px; }
/* Without min-width: 0 a grid item is as wide as its widest child, so one long
   line of code drags the whole page sideways. */
.layout > * { min-width: 0; }
@media (max-width: 900px) { .layout { grid-template-columns: minmax(0, 1fr); } }
.content h2 {
  font-size: 13px; letter-spacing: .14em; text-transform: uppercase; color: var(--dim);
  margin: 34px 0 12px; padding-bottom: 8px; border-bottom: 1px solid var(--edge);
}
.content h2:first-child { margin-top: 0; }
.content ul { padding-left: 20px; color: var(--muted); }
.content li { margin: 6px 0; }
.content li::marker { color: var(--accent-deep); }
aside .box {
  background: var(--raised); border: 1px solid var(--edge); border-radius: var(--radius);
  padding: 20px; position: sticky; top: 78px;
}
aside h2 { font-size: 12px; letter-spacing: .14em; text-transform: uppercase; color: var(--dim); margin: 0 0 12px; }
aside dl { margin: 0; display: grid; grid-template-columns: 1fr; gap: 12px; }
aside dt { font-size: 12px; letter-spacing: .06em; text-transform: uppercase; color: var(--dim); }
aside dd { margin: 2px 0 0; font-size: 14.5px; color: var(--ink); word-break: break-word; }
aside .checksum { font-family: "Cascadia Code", "SF Mono", Consolas, monospace; font-size: 11.5px; color: var(--muted); }
table { border-collapse: collapse; width: 100%; margin: 4px 0 10px; font-size: 15px; table-layout: fixed; }
th, td { text-align: left; padding: 9px 12px; border-bottom: 1px solid var(--edge); vertical-align: top;
  overflow-wrap: anywhere; }
th { color: var(--dim); font-weight: 600; width: 170px; }
.content p, .content li { overflow-wrap: anywhere; }
.code { border: 1px solid var(--edge); border-radius: var(--radius-sm); overflow: hidden; margin: 0 0 18px; }
.code .head {
  background: var(--raised-2); border-bottom: 1px solid var(--edge); padding: 8px 14px;
  font-size: 12px; letter-spacing: .08em; text-transform: uppercase; color: var(--dim);
}
pre { margin: 0; max-width: 100%; background: var(--raised); padding: 15px 16px; overflow-x: auto;
  font-size: 13.5px; line-height: 1.6; }
pre code { display: block; min-width: 0; }
code { font-family: "Cascadia Code", "SF Mono", Consolas, monospace; }
time { color: var(--dim); }
.who { color: var(--muted); font-size: 14.5px; margin: 14px 0 0; }

/* ---------- mobile: centred and symmetric ---------- */
@media (max-width: 720px) {
  .wrap { padding-left: var(--s3); padding-right: var(--s3); }
  .content, .detail-hero .wrap { padding-left: var(--s3); padding-right: var(--s3); }
  /* Cards keep the wide padding on a phone: the text was reading as if it were
     glued to its own border. */
  .panel { padding: var(--s3); }
  .hero .wrap { padding: var(--s6) var(--s4) var(--s5); text-align: center; }
  .hero .shot img, .hero .shot video { object-position: center; }
  /* The seam runs straight through the middle on a phone, so the text needs a
     denser scrim than the wide layout, where it sits beside the bright part. */
  .hero::before { background:
    radial-gradient(90% 60% at 50% 45%, rgba(10,16,22,.86), rgba(10,16,22,.78) 60%, rgba(10,16,22,.92)); }
  .hero .inner { max-width: 100%; margin: 0 auto; }
  .hero h1 { font-size: clamp(30px, 9vw, 40px); }
  .hero .lede { margin-left: auto; margin-right: auto; max-width: 40ch; }
  .eyebrow { margin-left: auto; margin-right: auto; }
  .actions { flex-direction: column; align-items: stretch; gap: var(--s2); }
  .actions .button { width: 100%; justify-content: center; }
  .stats { justify-content: space-between; gap: var(--s2) var(--s3); }
  .stats li { flex: 1 1 40%; align-items: center; text-align: center; }
  .panel { margin-top: calc(var(--s3) * -1); padding: var(--s3); }
  .controls { grid-template-columns: 1fr; }
  .toggles { flex-direction: column; align-items: center; gap: var(--s1); }
  .count { text-align: center; }
  .section-head { flex-direction: column; align-items: center; gap: 4px; text-align: center; }
  .strip, .cloud { justify-content: center; }
  .card { align-items: center; text-align: center; }
  .card .top { flex-direction: column; gap: var(--s1); }
  .card p.body { text-align: left; }
  .tags { justify-content: center; }
  .card .foot { justify-content: center; gap: var(--s3); }
  .cta { text-align: center; padding: var(--s4) var(--s3); }
  .cta .links { justify-content: center; }
  .cta .links .button { width: 100%; justify-content: center; }
  .detail-hero .wrap { text-align: center; }
  .detail-hero .top { flex-direction: column; gap: var(--s2); }
  .crumbs { text-align: center; }
  aside .box { position: static; }
  .content table, aside dl { font-size: 14px; }
  .content th { width: 40%; }
  /* A phone should not have to scroll a command sideways to read it. */
  .code pre { font-size: 12.5px; white-space: pre-wrap; overflow-wrap: anywhere; }
  .detail-hero img.icon { width: 60px; height: 60px; }
  footer .cols { flex-direction: column; align-items: center; text-align: center; }
  footer .links { justify-content: center; }
  .bar nav { gap: var(--s2); }
  .bar nav a:nth-of-type(2), .bar nav a:nth-of-type(3) { display: none; }
}

/* ---------- motion ---------- */
@keyframes drift { from { transform: translateX(-28px); } to { transform: translateX(28px); } }
@keyframes glow { 0%, 100% { opacity: .55; } 50% { opacity: 1; } }
@keyframes sheen { from { background-position: 0% 50%; } to { background-position: 200% 50%; } }

.reveal { opacity: 0; transform: translateY(18px);
  transition: opacity .45s cubic-bezier(.22,.75,.3,1), transform .45s cubic-bezier(.22,.75,.3,1); }
.reveal.in { opacity: 1; transform: none; }
.grid .card.reveal { transition-delay: calc(var(--i, 0) * 45ms); }
.hero .layers path:nth-child(1) { animation: drift 26s ease-in-out infinite alternate; }
.hero .layers path:nth-child(2) { animation: drift 34s ease-in-out infinite alternate-reverse; }
.hero .layers path:nth-child(3) { animation: drift 44s ease-in-out infinite alternate; }
.hero::before { animation: glow 14s ease-in-out infinite; }
.hero h1 i { background: linear-gradient(90deg, var(--accent), var(--accent-deep), var(--accent));
  background-size: 200% 100%; -webkit-background-clip: text; background-clip: text; color: transparent;
  animation: sheen 9s linear infinite; }
.card .top img { transition: transform .25s cubic-bezier(.22,.75,.3,1); }
.card:hover .top img { transform: rotate(-4deg) scale(1.06); }
.button.primary { background-size: 180% 100%; transition: background-position .35s ease, transform .12s ease; }
.button.primary:hover { background-position: 100% 50%; }
.card, .tag, .cloud button, .strip li { will-change: transform; }
.stats b { font-variant-numeric: tabular-nums; }

@media (prefers-reduced-motion: reduce) {
  html { scroll-behavior: auto; }
  .reveal, .reveal.in { opacity: 1; transform: none; transition: none; }
  .hero .layers path, .hero::before, .hero h1 i { animation: none; }
  .card:hover { transform: none; }
  .card:hover .top img { transform: none; }
}

/* ---------- footer ---------- */
footer { border-top: 1px solid var(--edge); margin-top: 56px; padding: 34px 0 60px; color: var(--dim); font-size: 14px; background: var(--raised); }
footer .cols { display: flex; flex-wrap: wrap; gap: 30px; justify-content: space-between; }
footer a { color: var(--muted); }
footer .note { max-width: 58ch; margin: 0; }
footer .links { display: flex; gap: 18px; flex-wrap: wrap; }
""".strip()

HERO_MEDIA = (
    '<img src="assets/img/hero-2400.webp" srcset="assets/img/hero-1280.webp 1280w, '
    'assets/img/hero-2400.webp 2400w" sizes="100vw" alt="" fetchpriority="high" decoding="async" '
    'style="background:#0a1016">'
    '<video id="hero-video" muted loop playsinline preload="none" aria-hidden="true" '
    'poster="assets/img/hero-2400.webp" hidden></video>'
)

HERO_SCRIPT = r"""
// The 4K hero loop plays on every screen, phones included. It is still skipped
// when motion is unwelcome or the connection is metered or slow — in those cases
// the still remains, which is the video's own first frame.
(function () {
  const video = document.getElementById('hero-video');
  if (!video) return;
  const motionOk = !window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const connection = navigator.connection || {};
  const cheapData = connection.saveData === true ||
    ['slow-2g', '2g', '3g'].includes(connection.effectiveType);
  if (!motionOk || cheapData) return;
  video.src = 'assets/video/hero-4k.mp4';
  const reveal = function () {
    video.hidden = false;
    const started = video.play();
    if (started && started.catch) started.catch(function () { video.hidden = true; });
  };
  video.addEventListener('loadeddata', reveal, { once: true });
  video.addEventListener('canplay', reveal, { once: true });
  // preload="none" means nothing is fetched until we ask, so ask.
  video.load();
})();
""".strip()

LAYER_ART = (
    '<svg class="layers" viewBox="0 0 1440 190" preserveAspectRatio="none" aria-hidden="true">'
    '<path d="M0 96 q180 -34 360 -8 q180 26 360 -6 q180 -32 360 4 q180 36 360 -10 V190 H0 Z" fill="#3d5568" opacity=".28"/>'
    '<path d="M0 130 q200 30 400 4 q200 -26 400 8 q200 34 640 -14 V190 H0 Z" fill="#4a6a80" opacity=".3"/>'
    '<path d="M0 164 q220 -24 440 2 q220 26 440 -6 q200 -28 560 8 V190 H0 Z" fill="#5b8298" opacity=".32"/>'
    "</svg>"
)

SCRIPT = r"""
const skills = JSON.parse(document.getElementById('skill-data').textContent);
const controls = ['q', 'agent', 'platform', 'category', 'quality'].map((id) => document.getElementById(id));
const toggles = ['offline', 'nosecrets'].map((id) => document.getElementById(id));
const grid = document.getElementById('grid');
const count = document.getElementById('count');

function matches(skill) {
  const [q, agent, platform, category, quality] = controls.map((el) => el.value);
  const [offline, noSecrets] = toggles.map((el) => el.checked);
  if (agent && !(skill.compatibility || []).includes(agent)) return false;
  if (platform && !(skill.platforms || []).includes(platform)) return false;
  if (category && skill.category !== category) return false;
  if (quality && skill.quality !== quality) return false;
  if (offline && (skill.security || {}).network_access !== 'none') return false;
  if (noSecrets && (skill.security || {}).requires_secrets !== false) return false;
  if (q) {
    const needle = q.toLowerCase();
    const hay = [skill.name, skill.displayName, skill.description, (skill.keywords || []).join(' ')]
      .join(' ').toLowerCase();
    if (!hay.includes(needle)) return false;
  }
  return true;
}

function apply() {
  let shown = 0;
  for (const card of grid.children) {
    const skill = skills.find((item) => item.name === card.dataset.name);
    const visible = matches(skill);
    card.hidden = !visible;
    if (visible) card.classList.add('in');
    if (visible) shown += 1;
  }
  count.textContent = shown === skills.length
    ? `${skills.length} skills`
    : `${shown} of ${skills.length} skills`;
  document.getElementById('empty').hidden = shown !== 0;
}

for (const el of [...controls, ...toggles]) {
  el.addEventListener(el.tagName === 'INPUT' && el.type !== 'checkbox' ? 'input' : 'change', apply);
}
for (const button of document.querySelectorAll('.cloud button')) {
  button.addEventListener('click', () => {
    controls[0].value = button.dataset.keyword;
    apply();
    document.getElementById('skills').scrollIntoView({ behavior: 'smooth', block: 'start' });
  });
}
apply();

// Download counts come from GitHub's public release API: one asset per skill
// version, counted by GitHub itself. Nothing is sent about the reader, and the
// page works unchanged when the request fails or is blocked.
async function loadInstalls() {
  let releases;
  try {
    const response = await fetch('https://api.github.com/repos/BEKO2210/SkillQuarry/releases');
    if (!response.ok) return;
    releases = await response.json();
  } catch (error) {
    return;
  }
  const counts = new Map();
  for (const release of releases) {
    for (const asset of release.assets || []) {
      const match = /^([a-z0-9-]+)-\d+\.\d+\.\d+\.tar\.gz$/.exec(asset.name);
      if (!match) continue;
      counts.set(match[1], (counts.get(match[1]) || 0) + (asset.download_count || 0));
    }
  }
  if (counts.size === 0) return;
  for (const element of document.querySelectorAll('[data-installs]')) {
    const value = counts.get(element.dataset.installs);
    if (value === undefined) continue;
    element.innerHTML = '<b>' + value.toLocaleString() + '</b> download' + (value === 1 ? '' : 's');
  }
  [...grid.children]
    .sort((a, b) => (counts.get(b.dataset.name) || 0) - (counts.get(a.dataset.name) || 0))
    .forEach((card) => grid.appendChild(card));
}
loadInstalls();
""".strip()

THEME_SCRIPT = r"""
(function () {
  const stored = localStorage.getItem('skillquarry-theme');
  const system = window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark';
  const root = document.documentElement;
  root.dataset.theme = stored || system;
  window.addEventListener('DOMContentLoaded', function () {
    const button = document.getElementById('theme');
    if (!button) return;
    const label = () => { button.textContent = root.dataset.theme === 'light' ? 'Dark' : 'Light'; };
    label();
    button.addEventListener('click', function () {
      root.dataset.theme = root.dataset.theme === 'light' ? 'dark' : 'light';
      localStorage.setItem('skillquarry-theme', root.dataset.theme);
      label();
    });
  });
})();
""".strip()

MOTION_SCRIPT = r"""
// Entrance animation and stat count-up. Both are progressive: without JavaScript,
// or with reduced motion requested, everything is simply visible immediately.
(function () {
  const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const targets = document.querySelectorAll('.card, .section-head, .strip, .cloud, .cta, .panel, .content h2, aside .box');
  if (reduced || !('IntersectionObserver' in window)) {
    targets.forEach((element) => element.classList.add('in'));
    return;
  }
  document.querySelectorAll('.grid').forEach((grid) => {
    [...grid.children].forEach((card, index) => card.style.setProperty('--i', index));
  });
  targets.forEach((element) => element.classList.add('reveal'));
  // Failsafe: whatever happens to the observer, nothing stays invisible.
  const showEverything = () => targets.forEach((element) => element.classList.add('in'));
  setTimeout(showEverything, 1500);
  window.addEventListener('beforeprint', showEverything);
  const observer = new IntersectionObserver((entries) => {
    for (const entry of entries) {
      if (!entry.isIntersecting) continue;
      entry.target.classList.add('in');
      observer.unobserve(entry.target);
    }
  }, { rootMargin: '0px 0px -8% 0px', threshold: 0.05 });
  targets.forEach((element) => observer.observe(element));

  for (const number of document.querySelectorAll('.stats b')) {
    const final = parseInt(number.textContent, 10);
    if (!Number.isFinite(final) || final === 0) continue;
    const started = performance.now();
    const duration = 900;
    const step = (now) => {
      const progress = Math.min(1, (now - started) / duration);
      const eased = 1 - Math.pow(1 - progress, 3);
      number.textContent = Math.round(final * eased).toLocaleString();
      if (progress < 1) requestAnimationFrame(step);
    };
    number.textContent = '0';
    requestAnimationFrame(step);
  }
})();
""".strip()

INSTALL_SCRIPT = r"""
// Same public source as the overview: GitHub's own per-asset download counter.
fetch('https://api.github.com/repos/BEKO2210/SkillQuarry/releases')
  .then((response) => (response.ok ? response.json() : []))
  .then((releases) => {
    const counts = new Map();
    for (const release of releases) {
      for (const asset of release.assets || []) {
        const match = /^([a-z0-9-]+)-\d+\.\d+\.\d+\.tar\.gz$/.exec(asset.name);
        if (match) counts.set(match[1], (counts.get(match[1]) || 0) + (asset.download_count || 0));
      }
    }
    for (const element of document.querySelectorAll('[data-installs]')) {
      const value = counts.get(element.dataset.installs);
      if (value !== undefined) {
        element.innerHTML = '<b>' + value.toLocaleString() + '</b> download' + (value === 1 ? '' : 's');
      }
    }
  })
  .catch(() => {});
""".strip()


def top_bar(depth: int) -> str:
    up = "../" * depth
    return f"""<div class="bar"><div class="wrap">
  <a class="mark" href="{up}index.html">
    <img src="{up}assets/img/icon-quarry.webp" alt="">
    <span>Skill<i>Quarry</i></span>
  </a>
  <nav>
    <a href="{up}index.html#skills">Skills</a>
    <a href="{up}maintainers/index.html">Maintainers</a>
    <a href="{SOURCE_URL}/blob/main/docs/SKILL-SPEC.md">Spec</a>
    <a href="{SOURCE_URL}">GitHub</a>
    <button class="ghost" id="theme" type="button">Light</button>
  </nav>
</div></div>"""


def style_token() -> str:
    """A fingerprint of the stylesheet, appended to its URL.

    Without it a browser can hold yesterday's CSS against today's HTML — which is
    exactly how a fixed layout kept looking broken on a phone that had already
    fetched the new page.
    """
    import hashlib
    return hashlib.sha256(STYLE.encode("utf-8")).hexdigest()[:10]


def page(title: str, description: str, body: str, *, depth: int = 0, scripts: str = "") -> str:
    up = "../" * depth
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<meta name="color-scheme" content="dark light">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<meta property="og:type" content="website">
<meta property="og:image" content="https://beko2210.github.io/SkillQuarry/assets/img/og.jpg">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="{up}assets/img/favicon.png" type="image/png">
<link rel="apple-touch-icon" href="{up}assets/img/icon-quarry.webp">
<link rel="stylesheet" href="{up}style.css?v={style_token()}">
<script>{THEME_SCRIPT}</script>
</head>
<body>
{top_bar(depth)}
{body}
<footer><div class="wrap cols">
  <p class="note">Generated from <code>registry/skills.json</code> by <code>tools/build_site.py</code>.
  Download counts come from GitHub's public release API — no cookies, no identifiers,
  nothing recorded about you.</p>
  <div class="links">
    <a href="{SOURCE_URL}">Source</a>
    <a href="{SOURCE_URL}/blob/main/CONTRIBUTING.md">Contributing</a>
    <a href="{SOURCE_URL}/blob/main/SECURITY.md">Security</a>
    <a href="{SOURCE_URL}/discussions">Discussions</a>
    <a href="{up}registry.json">registry.json</a>
  </div>
</div></footer>
<script>{MOTION_SCRIPT}</script>
{scripts}
</body>
</html>
"""


def icon_for(manifest: dict[str, Any], depth: int = 0, name: str | None = None) -> str | None:
    """The skill's mark: the rendered 3D tile when one exists, else its flat SVG.

    The 3D file is found by convention (assets/img/icon-<name>.webp), so a skill
    added tomorrow keeps working with nothing but its SVG — or with neither.
    """
    up = "../" * depth
    if name and (REPO / "assets" / "img" / f"icon-{name}.webp").is_file():
        return f"{up}assets/img/icon-{name}.webp"
    icon = manifest.get("icon")
    if not icon:
        return None
    return f"{up}assets/{Path(str(icon)).name}"


def gradient_for(name: str) -> str:
    """A deterministic fallback so a skill without artwork still looks intentional."""
    seed = sum(ord(character) for character in name)
    hue = seed % 360
    return (f"linear-gradient(135deg, hsl({hue} 32% 26%), hsl({(hue + 42) % 360} 38% 16%))")


def artwork_for(manifest: dict[str, Any], skill: dict[str, Any], depth: int = 0) -> str:
    """Card artwork, in order: the manifest's image, the skill's icon, a generated gradient.

    A skill added tomorrow needs none of them: the last step always works.
    """
    name = str(skill.get("name", ""))
    up = "../" * depth
    image = manifest.get("image")
    if image and (REPO / str(image)).is_file():
        return (f'<div class="art"><img src="{up}{esc(image)}" alt="" loading="lazy" '
                f'decoding="async"></div>')
    icon = icon_for(manifest, depth, name=name)
    if icon:
        return (f'<div class="art art-icon" style="background:{gradient_for(name)}">'
                f'<img src="{esc(icon)}" alt="" loading="lazy" decoding="async"></div>')
    return f'<div class="art" style="background:{gradient_for(name)}"></div>' 


def card(skill: dict[str, Any], manifest: dict[str, Any]) -> str:
    security = skill.get("security") or {}
    tests = skill.get("tests") or {}
    tags = [f'<span class="tag accent">{esc(CATEGORY_LABELS.get(skill.get("category"), skill.get("category")))}</span>']
    if tests.get("count"):
        tags.append(f'<span class="tag ok">{esc(tests["count"])} tests</span>')
    if security.get("network_access") == "none":
        tags.append('<span class="tag ok">offline</span>')
    if security.get("destructive_operations"):
        tags.append('<span class="tag warn">destructive</span>')
    for agent in skill.get("compatibility") or []:
        tags.append(f'<span class="tag">{esc(AGENT_LABELS.get(agent, agent))}</span>')
    icon = icon_for(manifest, name=str(skill.get("name")))
    tagline = manifest.get("tagline")
    return f"""      <article class="card" data-name="{esc(skill['name'])}">
        {artwork_for(manifest, skill)}
        <div class="top">
          {f'<img src="{esc(icon)}" alt="">' if icon else ''}
          <div>
            <h3><a href="skills/{esc(skill['name'])}.html">{esc(skill.get('displayName'))}</a></h3>
            {f'<p class="tagline">{esc(tagline)}</p>' if tagline else ''}
          </div>
        </div>
        <p class="body">{esc(skill.get('description'))}</p>
        <div class="tags">{''.join(tags)}</div>
        <div class="foot">
          <span>v{esc(skill.get('version'))}</span>
          <span class="installs" data-installs="{esc(skill['name'])}"></span>
        </div>
      </article>"""


def options(values: list[str], labels: dict[str, str], placeholder: str) -> str:
    parts = [f'<option value="">{esc(placeholder)}</option>']
    for value in values:
        parts.append(f'<option value="{esc(value)}">{esc(labels.get(value, value))}</option>')
    return "".join(parts)


def humanise(date: str | None) -> str:
    return date[:10] if date else "—"


def recently_updated(skills: list[dict[str, Any]], history: dict[str, Any], limit: int = 5) -> str:
    rows = sorted(
        ((str(s["name"]), str(s.get("displayName")), str(s.get("version")),
          (history.get(str(s["name"])) or {}).get("released"))
         for s in skills),
        key=lambda row: row[3] or "", reverse=True,
    )[:limit]
    items = "".join(
        f'<li><a href="skills/{esc(name)}.html">{esc(display)}</a>'
        f'<span class="when">v{esc(version)} · {esc(humanise(when))}</span></li>'
        for name, display, version, when in rows
    )
    return f'<ul class="strip">{items}</ul>'


def keyword_cloud(manifests: dict[str, dict[str, Any]], limit: int = 18) -> str:
    counts: dict[str, int] = {}
    for manifest in manifests.values():
        for keyword in manifest.get("keywords") or []:
            counts[str(keyword)] = counts.get(str(keyword), 0) + 1
    ranked = sorted(counts.items(), key=lambda item: (-item[1], item[0]))[:limit]
    buttons = "".join(
        f'<li><button type="button" data-keyword="{esc(word)}">{esc(word)}</button></li>'
        for word, _count in ranked
    )
    return f'<ul class="cloud">{buttons}</ul>'


def maintainer_index(manifests: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Maintainer handle -> their details and the skills they are responsible for."""
    people: dict[str, dict[str, Any]] = {}
    for name, manifest in sorted(manifests.items()):
        for person in manifest.get("maintainers") or []:
            handle = str(person.get("github"))
            entry = people.setdefault(handle, {"name": person.get("name"), "github": handle,
                                               "role": person.get("role"), "skills": []})
            entry["skills"].append(name)
    return people


def build_index(skills: list[dict[str, Any]], manifests: dict[str, dict[str, Any]],
                history: dict[str, Any]) -> str:
    agents = sorted({a for s in skills for a in (s.get("compatibility") or [])})
    platforms = sorted({p for s in skills for p in (s.get("platforms") or [])})
    categories = sorted({str(s.get("category")) for s in skills})
    qualities = sorted({str(s.get("quality")) for s in skills})
    total_tests = sum(int((s.get("tests") or {}).get("count") or 0) for s in skills)
    data = json.dumps(skills, ensure_ascii=False, sort_keys=True).replace("</", "<\\/")
    people = maintainer_index(manifests)

    maintainer_strip = '<ul class="strip">' + "".join(
        f'<li><a href="maintainers/{esc(handle)}.html">{esc(person["name"])}</a>'
        f'<span class="when">{len(person["skills"])} skill{"" if len(person["skills"]) == 1 else "s"}</span></li>'
        for handle, person in sorted(people.items())
    ) + "</ul>"

    body = f"""<header class="hero">
  <div class="shot">{HERO_MEDIA}</div>
  {LAYER_ART}
  <div class="wrap"><div class="inner">
    <p class="eyebrow">Open marketplace for agent skills</p>
    <h1>Build capabilities once. <span class="line">Share <i>intelligence</i> everywhere.</span></h1>
    <p class="lede">Reusable capabilities for AI coding agents — inspectable, tested,
      versioned, checksum-verified, and installable with one command. No dependencies,
      no telemetry, nothing hidden.</p>
    <div class="actions">
      <a class="button primary" href="#skills">Browse {len(skills)} skills</a>
      <a class="button secondary" href="{SOURCE_URL}#install-the-client">Install the client</a>
    </div>
    <ul class="stats">
      <li><b>{len(skills)}</b><span>skills</span></li>
      <li><b>{len(categories)}</b><span>categories</span></li>
      <li><b>{total_tests}</b><span>tests passing</span></li>
      <li><b>0</b><span>dependencies</span></li>
    </ul>
  </div></div>
</header>
<main class="wrap">
  <div class="panel" id="skills">
    <div class="controls">
      <div><label for="q">Search</label><input id="q" type="search" placeholder="name, description, keyword" autocomplete="off"></div>
      <div><label for="agent">Agent</label><select id="agent">{options(agents, AGENT_LABELS, "Any agent")}</select></div>
      <div><label for="platform">Platform</label><select id="platform">{options(platforms, {}, "Any platform")}</select></div>
      <div><label for="category">Category</label><select id="category">{options(categories, CATEGORY_LABELS, "Any category")}</select></div>
      <div><label for="quality">Quality</label><select id="quality">{options(qualities, {}, "Any level")}</select></div>
    </div>
    <div class="toggles">
      <label><input type="checkbox" id="offline"> needs no network of its own</label>
      <label><input type="checkbox" id="nosecrets"> needs no credentials</label>
    </div>
  </div>

  <p class="count" id="count">{len(skills)} skills</p>
  <div class="grid" id="grid">
{chr(10).join(card(skill, manifests[skill["name"]]) for skill in skills)}
  </div>
  <p class="empty" id="empty" hidden>No skill matches those filters.</p>

  <div class="section-head"><h2>Recently updated</h2><span>by version date</span></div>
  {recently_updated(skills, history)}

  <div class="section-head"><h2>Browse by keyword</h2></div>
  {keyword_cloud(manifests)}

  <div class="section-head"><h2>Maintainers</h2><a href="maintainers/index.html">All maintainers &rarr;</a></div>
  {maintainer_strip}

  <section class="cta">
    <div>
      <h2>Add your skill</h2>
      <p>A skill is a directory with a manifest, an agent-facing SKILL.md, tests and a test
         report. Scaffold one from the reference skill, open a pull request, and CI checks
         the specification, the checksums and the registry for you.</p>
    </div>
    <div class="links">
      <a class="button primary" href="{SOURCE_URL}/blob/main/CONTRIBUTING.md">Contributing</a>
      <a class="button secondary" href="{SOURCE_URL}/blob/main/docs/SKILL-SPEC.md">Skill specification</a>
      <a class="button secondary" href="{SOURCE_URL}/issues/new/choose">Propose a skill</a>
      <a class="button secondary" href="{SOURCE_URL}/discussions">Discussions</a>
    </div>
  </section>
</main>
<script type="application/json" id="skill-data">{data}</script>"""
    return page("SkillQuarry — the open marketplace for agent skills",
                "Discover, inspect and install reusable capabilities for AI coding agents.",
                body, scripts=f"<script>{SCRIPT}</script>\n<script>{HERO_SCRIPT}</script>")


def build_detail(skill: dict[str, Any], manifest: dict[str, Any],
                 history: dict[str, Any] | None = None) -> str:
    security = skill.get("security") or {}
    tests = skill.get("tests") or {}
    name = str(skill["name"])
    source = f"{SOURCE_URL}/tree/main/{skill['path']}"
    icon = icon_for(manifest, depth=1, name=name)
    banner = manifest.get("banner")

    facts = [
        ("Version", skill.get("version")),
        ("Category", CATEGORY_LABELS.get(skill.get("category"), skill.get("category"))),
        ("Quality", skill.get("quality")),
        ("License", skill.get("license")),
        ("Agents", ", ".join(AGENT_LABELS.get(a, a) for a in skill.get("compatibility") or []) or "—"),
        ("Platforms", ", ".join(skill.get("platforms") or []) or "—"),
        ("Tests", f"{tests.get('count', '—')} — {tests.get('coverage', 'no coverage figure')}"),
        ("Needs installed", ", ".join((skill.get("requires") or {}).get("binaries") or []) or "nothing extra"),
        ("Network access", security.get("network_access", "undeclared")),
        ("Credentials", "required" if security.get("requires_secrets") else "none"),
        ("Writes outside the repository", "yes" if security.get("writes_outside_repository") else "no"),
        ("Irreversible operations", "; ".join(security.get("destructive_operations") or []) or "none declared"),
        ("Independently reviewed", security.get("reviewed_by", "not recorded")),
    ]
    fact_list = "\n".join(
        f"      <div><dt>{esc(key)}</dt><dd>{esc(value)}</dd></div>" for key, value in facts
    )

    people = manifest.get("maintainers") or []
    who = ""
    if people:
        links = ", ".join(
            f'<a href="../maintainers/{esc(person.get("github"))}.html">{esc(person.get("name"))}</a>'
            for person in people
        )
        who = f'<p class="who">Maintained by {links} · <span class="installs" data-installs="{esc(name)}"></span></p>'

    highlights = manifest.get("highlights") or []
    highlight_block = ""
    if highlights:
        items = "\n".join(f"      <li>{esc(item)}</li>" for item in highlights)
        highlight_block = f"    <h2>What it does</h2>\n    <ul>\n{items}\n    </ul>\n"

    quickstart = manifest.get("quickstart")
    quickstart_block = ""
    if quickstart:
        quickstart_block = (
            '    <h2>Quickstart</h2>\n'
            '    <div class="code"><div class="head">shell</div>'
            f"<pre><code>{esc(quickstart)}</code></pre></div>\n"
        )

    relations = ""
    dependencies = skill.get("dependencies") or manifest.get("dependencies") or []
    partners = skill.get("composes_with") or manifest.get("composes_with") or []
    if dependencies or partners:
        rows = "".join(
            f'      <tr><th>needs</th><td><a href="{esc(item["name"])}.html">{esc(item["name"])}</a>'
            f'{" &ge; " + esc(item["minimum_version"]) if item.get("minimum_version") else ""}'
            f'{" — " + esc(item["reason"]) if item.get("reason") else ""}</td></tr>'
            for item in dependencies
        ) + "".join(
            f'      <tr><th>works with</th><td><a href="{esc(partner)}.html">{esc(partner)}</a></td></tr>'
            for partner in partners
        )
        relations = f"    <h2>Relationships</h2>\n    <table>\n{rows}\n    </table>\n"

    checks = skill.get("verifications") or manifest.get("verifications") or []
    verified = ""
    if checks:
        items = "".join(
            f"      <tr><th><time>{esc(item['date'])}</time></th><td>"
            f"<strong>{esc(item['result'].replace('-', ' '))}</strong> — {esc(item['by'])}<br>"
            f"{esc(item['method'])}"
            f"{'<br>' + esc(item['findings']) if item.get('findings') else ''}"
            f"{' · <a href=\'' + esc(item['url']) + '\'>evidence</a>' if item.get('url') else ''}"
            "</td></tr>"
            for item in checks
        )
        verified = f"    <h2>Independent verification</h2>\n    <table>\n{items}\n    </table>\n"

    versions = (history or {}).get("versions") or []
    history_block = ""
    if versions:
        rows = "".join(
            f"      <tr><th>v{esc(item['version'])}</th><td><time>{esc(humanise(item['date']))}</time></td></tr>"
            for item in versions
        )
        history_block = (
            "    <h2>Version history</h2>\n"
            f"    <table>\n{rows}\n    </table>\n"
            f'    <p><a href="{esc(SOURCE_URL)}/commits/main/{esc(skill["path"])}">Full commit history &rarr;</a></p>\n'
        )

    links = [f'<a href="{esc(source)}">Source</a>',
             f'<a href="{esc(source)}/README.md">Documentation</a>',
             f'<a href="{esc(source)}/SKILL.md">SKILL.md</a>']
    if tests.get("report"):
        links.append(f'<a href="{esc(source)}/{esc(tests["report"])}">Test report</a>')

    body = f"""<header class="detail-hero"><div class="wrap">
  <p class="crumbs"><a href="../index.html">Skills</a> / {esc(skill.get('displayName'))}</p>
  <div class="top">
    {f'<img class="icon" src="{esc(icon)}" alt="">' if icon else ''}
    <div>
      <h1>{esc(skill.get('displayName'))}</h1>
      {f'<p class="subtitle">{esc(manifest["tagline"])}</p>' if manifest.get('tagline') else ''}
    </div>
  </div>
  {who}
</div></header>
<main class="wrap">
  <div class="layout">
    <div class="content">
      {f'<img class="banner" src="../{esc(banner)}" alt="{esc(skill.get("displayName"))}" style="width:100%;border-radius:14px;border:1px solid var(--edge);margin:0 0 26px">' if banner else ''}
      <h2>Overview</h2>
      <p>{esc(skill.get('description'))}</p>
{highlight_block}    <h2>Install</h2>
    <div class="code"><div class="head">shell</div><pre><code>git clone {esc(SOURCE_URL)}.git
cd SkillQuarry/cli &amp;&amp; ./install.sh
skillquarry info {esc(name)}
skillquarry install {esc(name)}</code></pre></div>
    <p>Installation verifies the checksum in the sidebar before running the skill's own installer.</p>
{quickstart_block}{relations}{verified}{history_block}    <h2>Read next</h2>
    <p>{' · '.join(links)}</p>
    </div>
    <aside>
      <div class="box">
        <h2>Facts</h2>
        <dl>
{fact_list}
          <div><dt>Checksum</dt><dd class="checksum">{esc(skill.get('checksum'))}</dd></div>
        </dl>
      </div>
    </aside>
  </div>
</main>"""
    return page(f"{skill.get('displayName')} — SkillQuarry", str(skill.get("description", "")),
                body, depth=1, scripts=f"<script>{INSTALL_SCRIPT}</script>")


def build_maintainer(handle: str, person: dict[str, Any], skills: dict[str, dict[str, Any]],
                     manifests: dict[str, dict[str, Any]]) -> str:
    cards = "\n".join(
        f"""      <article class="card">
        <div class="top">
          {f'<img src="{esc(icon_for(manifests[name], depth=1, name=name))}" alt="">' if icon_for(manifests[name], name=name) else ''}
          <div><h3><a href="../skills/{esc(name)}.html">{esc(skills[name].get('displayName'))}</a></h3></div>
        </div>
        <p class="body">{esc(skills[name].get('description'))}</p>
        <div class="tags"><span class="tag accent">{esc(CATEGORY_LABELS.get(skills[name].get('category'), skills[name].get('category')))}</span></div>
      </article>"""
        for name in person["skills"] if name in skills
    )
    body = f"""<header class="detail-hero"><div class="wrap">
  <p class="crumbs"><a href="../index.html">Skills</a> / <a href="index.html">Maintainers</a> / {esc(person.get('name'))}</p>
  <div class="top"><div>
    <h1>{esc(person.get('name'))}</h1>
    <p class="subtitle">{esc(person.get('role') or 'maintainer')}</p>
  </div></div>
  <p class="who"><a href="https://github.com/{esc(handle)}">@{esc(handle)}</a> ·
     maintains {len(person['skills'])} skill{'' if len(person['skills']) == 1 else 's'}</p>
</div></header>
<main class="wrap">
  <div class="grid" style="margin-top:34px">
{cards}
  </div>
</main>"""
    return page(f"{person.get('name')} — SkillQuarry", f"Skills maintained by {person.get('name')}.",
                body, depth=1)


def build_maintainer_index(people: dict[str, dict[str, Any]]) -> str:
    cards = "\n".join(
        f"""      <article class="card">
        <div class="top"><div>
          <h3><a href="{esc(handle)}.html">{esc(person.get('name'))}</a></h3>
          <p class="tagline">{esc(person.get('role') or 'maintainer')}</p>
        </div></div>
        <p class="body">Maintains {', '.join(esc(s) for s in person['skills'])}.</p>
        <div class="tags"><span class="tag">@{esc(handle)}</span></div>
      </article>"""
        for handle, person in sorted(people.items())
    )
    body = f"""<header class="detail-hero"><div class="wrap">
  <p class="crumbs"><a href="../index.html">Skills</a> / Maintainers</p>
  <div class="top"><div>
    <h1>Maintainers</h1>
    <p class="subtitle">The people responsible for the skills in this quarry</p>
  </div></div>
</div></header>
<main class="wrap">
  <div class="grid" style="margin-top:34px">
{cards}
  </div>
</main>"""
    return page("Maintainers — SkillQuarry", "The people responsible for the skills in this quarry.",
                body, depth=1)


def render() -> dict[str, str]:
    """Every generated file, as path-relative-to-site -> content."""
    skills = load_registry()
    manifests = {str(skill["name"]): load_manifest(skill) for skill in skills}
    history = load_history()
    by_name = {str(skill["name"]): skill for skill in skills}
    people = maintainer_index(manifests)
    api = {
        "api_version": 1,
        "documentation": f"{SOURCE_URL}/blob/main/docs/REGISTRY-API.md",
        "archive_base": f"{SOURCE_URL}/releases/latest/download",
        "repository": SOURCE_URL,
        "skills": skills,
    }
    files = {
        # A stable, versioned endpoint an agent can read without scraping HTML.
        "api/v1/skills.json": json.dumps(api, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        ".well-known/skillquarry.json": json.dumps({
            "name": "SkillQuarry",
            "registry": "https://beko2210.github.io/SkillQuarry/api/v1/skills.json",
            "archive_base": f"{SOURCE_URL}/releases/latest/download",
            "documentation": f"{SOURCE_URL}/blob/main/docs/REGISTRY-API.md",
            "client": f"{SOURCE_URL}/tree/main/cli",
        }, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        "index.html": build_index(skills, manifests, history),
        "style.css": STYLE + "\n",
        "registry.json": json.dumps({"schema_version": 2, "skills": skills}, indent=2,
                                    ensure_ascii=False, sort_keys=True) + "\n",
        ".nojekyll": "",
    }
    for skill in skills:
        name = str(skill["name"])
        files[f"skills/{name}.html"] = build_detail(skill, manifests[name], history.get(name))
        files[f"api/v1/skills/{name}.json"] = json.dumps(
            {**skill, "history": history.get(name, {})}, indent=2, ensure_ascii=False, sort_keys=True
        ) + "\n"
    files["maintainers/index.html"] = build_maintainer_index(people)
    for handle, person in people.items():
        files[f"maintainers/{handle}.html"] = build_maintainer(handle, person, by_name, manifests)
    for asset in sorted(ASSETS.glob("*.svg")):
        files[f"assets/{asset.name}"] = asset.read_text("utf-8")
    return files


def binary_files() -> dict[str, bytes]:
    """Images are copied verbatim; they are not generated, only carried."""
    found: dict[str, bytes] = {}
    for folder in ("img", "video", "fonts"):
        for asset in sorted((ASSETS / folder).glob("*")):
            if asset.is_file():
                found[f"assets/{folder}/{asset.name}"] = asset.read_bytes()
    return found


TEXT_SUFFIXES = {".html", ".css", ".json", ".svg", ".js", ""}


def current() -> dict[str, str]:
    if not SITE.is_dir():
        return {}
    found = {}
    for path in sorted(SITE.rglob("*")):
        if path.is_file() and path.suffix in TEXT_SUFFIXES:
            found[path.relative_to(SITE).as_posix()] = path.read_text("utf-8")
    return found


def current_binaries() -> dict[str, bytes]:
    if not SITE.is_dir():
        return {}
    return {
        path.relative_to(SITE).as_posix(): path.read_bytes()
        for path in sorted(SITE.rglob("*"))
        if path.is_file() and path.suffix not in TEXT_SUFFIXES
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if site/ differs from what would be generated")
    args = parser.parse_args(argv)

    try:
        files = render()
        images = binary_files()
    except SiteError as exc:
        print(f"build_site: {exc}", file=sys.stderr)
        return 2

    existing = current()
    if args.check:
        if existing != files or current_binaries() != images:
            existing_images = current_binaries()
            all_new = {**files, **images}
            all_old = {**existing, **existing_images}
            missing = sorted(set(all_new) - set(all_old))
            extra = sorted(set(all_old) - set(all_new))
            changed = sorted(k for k in set(all_new) & set(all_old) if all_new[k] != all_old[k])
            print("build_site: site/ is out of date", file=sys.stderr)
            for label, items in (("missing", missing), ("stale", changed), ("unexpected", extra)):
                if items:
                    print(f"  {label}: {', '.join(items)}", file=sys.stderr)
            print("  run `python3 tools/build_site.py` and commit the result", file=sys.stderr)
            return EXIT_STALE
        print(f"build_site: site/ is up to date ({len(files) + len(images)} files)")
        return 0

    if SITE.exists():
        shutil.rmtree(SITE)
    for relative, content in files.items():
        target = SITE / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    for relative, blob in images.items():
        target = SITE / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(blob)
    print(f"build_site: wrote {len(files) + len(images)} files to site/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
